services:
  - type: web
    name: mateubank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python MateuBank.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
